#!/bin/bash
echo -e "\nthe number of files are $#\n"
# $# is used for the number of argument sent to the script
if [ "$#" -lt "3" ]; then
# -lt command will compare that if $# is less than 3 or not
echo -e "\n ERROR MESSAGE \n"
exit 1
elif [ "$#" -eq "3" ] && [ "$*"=-f ]; then
# -eq command will compare that if $# is equal to 3 or not
# $* is used for all the arguments sent to the script 
unset -v latest
for file in "$Week3"; do
if [ "$1" -nt "$2" ] && [ "$1" -nt "$3"]; then
# -nt command is used to compare which is the newer one
echo -e "\n"$1" is the newer file\n"
elif [ "$2" -nt "$1" ] && [ "$2" -nt "$3" ]; then
echo -e "\n "$2" is the newer file \n"
elif [ "$3" -nt "$1" ] && [ "$3" -nt "$2" ]; then
echo -e "\n "$3" is the newer file\n"
exit 1
fi
done
elif [ "$#" -gt "3" ]; then
# -gt command is used to compare which is greater than
echo -e "\n ERROR \n"
exit 1
fi
exit 0