#!/bin/bash
for (( i=1;i<=1000;i=i+3 ))
# in this we allow a loop to run by giving it an initial value 1 and allow it to run until its value is lesser than or equal to 1000 and also we increase it after every turn by 3  
do
echo "$i"
done
exit 0